# http://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.


# A: 4613732

TERM_LIMIT = 4000000

def p2
  i = 1
  sum = 0
  while fib(i) < TERM_LIMIT
    sum = fib(i) + sum if fib(i) % 2 == 0
    i = i + 1
  end
  sum
end

def fib(n)
  f0 = 1 # By definition
  f1 = 2 # By definition
  return f0 if n == 1
  return f1 if n == 2

  term = 0

  (3..n).each do |k|
    term = f0 + f1
    f0 = f1
    f1 = term
  end

  term
end

puts p2